version: "3.7"

networks:
  app-net:
    driver: bridge
    
services:
  app:
    image: boardgame-run
    ports:
      - "8080:8080"
    networks:
      - app-net
    links:
      - db:db

  db:
    image: boardgame-db
    ports:
      - "5984:5984"
    networks:
      - app-net

  setup-db:
    depends_on:
      - db
    volumes:
      - ./db:/db
    image: byrnedo/alpine-curl
    command: ./db/setup.sh
    links:
      - db:db
    networks:
      - app-net